import { getDictionary } from '@/lib/i18n/get-dictionary'
import { Locale } from '@/lib/i18n/i18n-config'
import { IProjectType, TYPE_CODING_LESSON, TYPE_CODING_WEEK, TYPE_COLLEGE_LESSON, TYPE_ORIGINAL } from './project-type.data'
import { OWNER_CONFIGS } from './owener-config'

export type IProject = {
  id: string
  type: IProjectType
  tags: string[]
  title: string
  description: string
  date: string
  links: {
    github?: string
    figma?: string
    site?: string
  }
  images: string[]
}

export async function getProjectsData(lang: Locale): Promise<IProject[]> {
  const dictionary = await getDictionary(lang)
  const t = dictionary.project.data

  return ([
    {
      id: 'alura-courses',
      type: TYPE_CODING_LESSON,
      tags: ['angular', 'regex', 'html', 'css', 'javascript', 'ux', 'ui'],
      date: '2021-11-25T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/project-studies/tree/main/alura/courses-alura`,
        figma: '',
        site: '',
      },
      images: ['thumb.webp'],
      title: t['alura-courses'].title,
      description: t['alura-courses'].description,
    },
    {
      id: 'rocketseat-bootcamp',
      type: TYPE_CODING_LESSON,
      tags: ['html', 'css', 'javascript', 'react', 'nextjs'],
      date: '2023-01-10T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/project-studies/tree/main/rocketseat/rockeseat-bootcamp`,
        figma: '',
        site: '',
      },
      images: ['thumb.webp'],
      title: t['rocketseat-bootcamp'].title,
      description: t['rocketseat-bootcamp'].description,
    },
    {
      id: 'rocketseat-challenge-01-todo-list',
      type: TYPE_CODING_LESSON,
      tags: ['html', 'css', 'javascript', 'react', 'vite'],
      date: '2023-06-02T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/rocket-seat-challenges/tree/main/01-to-do-list`,
        figma: 'https://www.figma.com/file/0n0zDN7zbzhRbaEO74Xesx/ToDo-List/duplicate',
        site: 'https://challenge-01.felipescherer.com     ',
      },
      images: [`thumb.webp`],
      title: t['rocketseat-challenge-01-todo-list'].title,
      description: t['rocketseat-challenge-01-todo-list'].description,
    },
    {
      id: 'rocketseat-challenge-02-coffee-delivery',
      type: TYPE_CODING_LESSON,
      tags: ['html', 'css', 'javascript', 'react', 'vite'],
      date: '2023-06-24T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/rocket-seat-challenges/tree/main/02-coffee-delivery`,
        figma: 'https://www.figma.com/file/5yT9ZzZmRQRS4yivGGB3pl/Coffee-Delivery/duplicate',
        site: 'https://challenge-02.felipescherer.com',
      },
      images: ['overview.gif', 'overview-mobile.gif'],
      title: t['rocketseat-challenge-02-coffee-delivery'].title,
      description: t['rocketseat-challenge-02-coffee-delivery'].description,
    },
    {
      id: 'alura-animal-quiz',
      type: TYPE_CODING_WEEK,
      tags: ['react', 'nextjs', 'html', 'css', 'javascript'],
      date: '2021-01-25T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/project-studies/tree/main/alura/alura-quiz`,
        figma: '',
        site: 'https://alura-quiz-ofelipescherer.vercel.app',
      },
      images: ['overview.gif', 'thumb.webp'],
      title: t['alura-animal-quiz'].title,
      description: t['alura-animal-quiz'].description,
    },
    {
      id: 'alura-game-dev',
      type: TYPE_CODING_WEEK,
      tags: ['javascript', 'p5', 'game'],
      date: '2020-06-22T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/project-studies/tree/main/alura/game-dev`,
        figma: '',
        site: '',
      },
      images: ['overview.gif'],
      title: t['alura-game-dev'].title,
      description: t['alura-game-dev'].description,
    },
    {
      id: 'dev-superior-fsdelivery-sds2',
      type: TYPE_CODING_WEEK,
      tags: ['html', 'css', 'javascript', 'react', 'react-native', 'java-spring'],
      date: '2021-01-15T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/project-studies/tree/main/dev-superior/fsdelivery-sds2`,
        figma: '',
        site: 'https://felipescherer-fsdelivery.netlify.app',
      },
      images: ['homepage.webp', 'dashboard.webp', 'recipe-getting.webp', 'maps.webp', 'mobile.webp', 'mobile-pedidos.webp', 'mobile-dashboard.webp', 'mobile-checked.webp'],
      title: t['dev-superior-fsdelivery-sds2'].title,
      description: t['dev-superior-fsdelivery-sds2'].description,
    },
    {
      id: 'rocketseat-nlw-04',
      type: TYPE_CODING_WEEK,
      tags: ['html', 'css', 'javascript', 'react', 'nextjs'],
      date: '2021-02-15T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/project-studies/tree/main/rocketseat/nlw-04-move-it`,
        figma: '',
        site: 'https://moveit-felipescherer.vercel.app',
      },
      images: ['homepage.webp', 'level.webp', 'leve-up.webp', 'profile.webp', 'challenge.webp', 'desafio.webp', 'dark-mode-btn.webp', 'dark-mode.webp'],
      title: t['rocketseat-nlw-04'].title,
      description: t['rocketseat-nlw-04'].description,
    },
    {
      id: 'rocketseat-nlw-05',
      type: TYPE_CODING_WEEK,
      tags: ['html', 'css', 'javascript', 'react', 'react-native'],
      date: '2021-02-15T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/project-studies/tree/main/rocketseat/nlw-05-plant-manager`,
        figma: '',
        site: '',
      },
      images: ['thumb.webp'],
      title: t['rocketseat-nlw-05'].title,
      description: t['rocketseat-nlw-05'].description,
    },
    {
      id: 'rocketseat-nlw-06',
      type: TYPE_CODING_WEEK,
      tags: ['html', 'css', 'javascript', 'react', 'nextjs', 'firebase'],
      date: '2021-06-26T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/project-studies/tree/main/rocketseat/nlw-06-let-me-ask`,
        figma: '',
        site: 'https://letmeask-aulas-45172.web.app',
      },
      images: ['homepage.webp', 'room-id.webp', 'comment.webp', 'saved-comment.webp'],
      title: t['rocketseat-nlw-06'].title,
      description: t['rocketseat-nlw-06'].description,
    },
    {
      id: 'rocketseat-nlw-setup-habits',
      type: TYPE_CODING_WEEK,
      tags: ['html', 'css', 'javascript', 'react', 'backend', 'fast-api'],
      date: '2023-01-20T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/project-studies/tree/main/rocketseat/nlw-setup-habits`,
        figma: '',
        site: 'https://nlw-setup-habits-dun.vercel.app',
      },
      images: ['thumb.webp', 'habit.webp'],
      title: t['rocketseat-nlw-setup-habits'].title,
      description: t['rocketseat-nlw-setup-habits'].description,
    },
    {
      id: 'college-algorithm-best-fit',
      type: TYPE_COLLEGE_LESSON,
      tags: ['python', 'algorithm'],
      date: '2020-10-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/algorithm-best-fit`,
        figma: '',
        site: '',
      },
      images: ['thumb.webp'],
      title: t['college-algorithm-best-fit'].title,
      description: t['college-algorithm-best-fit'].description,
    },
    {
      id: 'college-aps-1',
      type: TYPE_COLLEGE_LESSON,
      tags: ['html', 'css'],
      date: '2019-03-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/aps/aps-01-desenvolvimento-em-ambiente-web`,
        figma: '',
        site: '',
      },
      images: ['overview.gif', 'aboutus.webp', 'reciclagem.webp', 'news.webp', 'form.webp', 'ecopontos.webp', 'app.webp', 'rrr.webp'],
      title: t['college-aps-1'].title,
      description: t['college-aps-1'].description,
    },
    {
      id: 'college-aps-2',
      type: TYPE_COLLEGE_LESSON,
      tags: ['python'],
      date: '2019-10-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/aps/aps-02-indroducao-a-programacao-estruturada`,
        figma: '',
        site: '',
      },
      images: ['overview.gif', 'thumb.webp'],
      title: t['college-aps-2'].title,
      description: t['college-aps-2'].description,
    },
    {
      id: 'college-aps-3',
      type: TYPE_COLLEGE_LESSON,
      tags: ['java'],
      date: '2020-03-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/aps/aps-03-programacao-orientada-a-objetos`,
        figma: '',
        site: '',
      },
      images: ['overview.gif'],
      title: t['college-aps-3'].title,
      description: t['college-aps-3'].description,
    },
    {
      id: 'college-aps-4',
      type: TYPE_COLLEGE_LESSON,
      tags: ['java'],
      date: '2020-10-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/aps/aps-04-aplicacao-orientacao-a-objetos`,
        figma: '',
        site: '',
      },
      images: ['home.webp', 'home-lib.webp', 'editoras.webp', 'database.webp'],
      title: t['college-aps-4'].title,
      description: t['college-aps-4'].description,
    },
    {
      id: 'college-aps-5',
      type: TYPE_COLLEGE_LESSON,
      tags: ['react', 'javascript', 'html', 'css'],
      date: '2021-03-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/aps/aps-05-redes-e-computadores`,
        figma: '',
        site: '',
      },
      images: ['login.webp', 'instances.webp', 'chat.webp', 'chat02.webp'],
      title: t['college-aps-5'].title,
      description: t['college-aps-5'].description,
    },
    {
      id: 'college-aps-6',
      type: TYPE_COLLEGE_LESSON,
      tags: ['linux'],
      date: '2021-10-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/aps/aps-06-sistemas-operacionais`,
        figma: '',
        site: '',
      },
      images: ['folder.webp', 'precos.webp', 'relatorio.webp', 'relatorio-servidor.webp'],
      title: t['college-aps-6'].title,
      description: t['college-aps-6'].description,
    },
    {
      id: 'college-aps-7',
      type: TYPE_COLLEGE_LESSON,
      tags: ['uml'],
      date: '2022-03-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/aps/aps-07-engenharia-de-software`,
        figma: '',
        site: '',
      },
      images: ['diagrama.webp'],
      title: t['college-aps-7'].title,
      description: t['college-aps-7'].description,
    },
    {
      id: 'college-aps-8',
      type: TYPE_COLLEGE_LESSON,
      tags: ['backend', 'fast-api'],
      date: '2022-10-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/aps/aps-08-sistemas-distribuidos`,
        figma: '',
        site: '',
      },
      images: ['home.webp', 'hproxy.webp', 'load-balancer.webp'],
      title: t['college-aps-8'].title,
      description: t['college-aps-8'].description,
    },
    {
      id: 'college-atm-simulation',
      type: TYPE_COLLEGE_LESSON,
      tags: ['python'],
      date: '2020-10-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/simulacao-caixa-eletronico`,
        figma: '',
        site: '',
      },
      images: ['relatorio.webp', 'running.webp'],
      title: t['college-atm-simulation'].title,
      description: t['college-atm-simulation'].description,
    },
    {
      id: 'college-computer-science-final-paper',
      type: TYPE_COLLEGE_LESSON,
      tags: ['html', 'css', 'javascript', 'react', 'fast-api'],
      date: '2022-11-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/tcc`,
        figma: 'https://www.figma.com/file/iKllJp1aDboNXpVOg5EaSc/Javi?t=L0Crz5jFiKMfRxix-1',
        site: 'http://javi.app.br',
      },
      images: ['overview.gif', 'homepage.webp', 'acounts.webp', 'dashboard.webp', 'saved.webp', 'movie-details.webp', 'dark-mode.webp'],
      title: t['college-computer-science-final-paper'].title,
      description: t['college-computer-science-final-paper'].description,
    },
    {
      id: 'college-data-structures',
      type: TYPE_COLLEGE_LESSON,
      tags: ['python'],
      date: '2020-10-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/data-structures`,
        figma: '',
        site: '',
      },
      images: ['infixposfix.webp', 'recursion.webp', 'convention.webp', 'hanoitower.webp', 'sorting-algorithms.webp'],
      title: t['college-data-structures'].title,
      description: t['college-data-structures'].description,
    },
    {
      id: 'college-ellipse-transformation',
      type: TYPE_COLLEGE_LESSON,
      tags: ['python'],
      date: '2021-10-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/ellipse-transformation`,
        figma: '',
        site: '',
      },
      images: ['overview.gif', 'homepage.webp', 'transformed.webp'],
      title: t['college-ellipse-transformation'].title,
      description: t['college-ellipse-transformation'].description,
    },
    {
      id: 'college-image-thresholding',
      type: TYPE_COLLEGE_LESSON,
      tags: ['java'],
      date: '2021-01-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/algorithm-thresholding`,
        figma: '',
        site: '',
      },
      images: ['thumb.webp', 'image-color.webp', 'image-black-white.webp', 'matriz.webp', 'histograma.webp', 'graph.webp'],
      title: t['college-image-thresholding'].title,
      description: t['college-image-thresholding'].description,
    },
    {
      id: 'college-lights-out',
      type: TYPE_COLLEGE_LESSON,
      tags: ['java'],
      date: '2021-03-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/lights-out`,
        figma: '',
        site: '',
      },
      images: ['solver-2.webp', 'solver.webp', 'pt-instructions.webp', 'en-instructions.webp'],
      title: t['college-lights-out'].title,
      description: t['college-lights-out'].description,
    },
    {
      id: 'college-linear-systeam-solver',
      type: TYPE_COLLEGE_LESSON,
      tags: ['python'],
      date: '2021-10-01T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/college-projects/tree/main/algorithm-linear-system-solver`,
        figma: '',
        site: '',
      },
      images: ['code.webp', 'result.webp', 'result-2.webp', 'result-3.webp', 'result-4.webp'],
      title: t['college-linear-systeam-solver'].title,
      description: t['college-linear-systeam-solver'].description,
    },
    {
      id: 'pokedex',
      type: TYPE_ORIGINAL,
      tags: ['react', 'figma', 'javascript', 'next', 'css', 'html'],
      date: '2023-01-29T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/pokedex`,
        figma: 'https://www.figma.com/file/JtsrGKsMNAnLKqVKBqnBad/Pokedex-APP?node-id=0-1&t=FUvofI6UnU3Pep3a-0',
        site: 'https://pokedex-felipescherer.vercel.app',
      },
      images: ['overview-opt.gif', 'homepage.webp', 'pokelist.webp', 'pokedetail.webp', 'pokedetail-2.webp', 'pokedetail-3.webp'],
      title: t['pokedex'].title,
      description: t['pokedex'].description,
    },
    {
      id: 'portifolio-v2',
      type: TYPE_ORIGINAL,
      tags: ['react', 'figma', 'javascript', 'next', 'css', 'html'],
      date: '2023-02-25T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/portifolio`,
        figma: 'https://www.figma.com/file/9LKjRjHQrDtWNbydqZygxf/Project?t=zyrOwueQfx7S4WIN-1',
        site: 'https://www.felipescherer.com/pt',
      },
      images: ['overview-home-opt.gif', 'overview-2-opt.gif', 'image.webp'],
      title: t['portifolio-v2'].title,
      description: t['portifolio-v2'].description,
    },
    {
      id: 'rpg',
      type: TYPE_ORIGINAL,
      tags: ['javascript', 'css', 'html', 'angular'],
      date: '2021-07-25T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/rpg-whitn`,
        figma: '',
        site: 'https://fescherer.github.io/rpg-whitn',
      },
      images: ['overview.gif', 'overview-rules.gif', 'homepage.webp', 'mechanics.webp', 'attributes.webp', 'beziel.webp', 'penemue.webp', 'baraqiel.webp', 'asbel.webp', 'af.webp', 'inventory.webp', 'stability.webp', 'weapons.webp', 'character.webp', 'textareas.webp'],
      title: t['rpg'].title,
      description: t['rpg'].description,
    },
    {
      id: 'rpg-v2',
      type: TYPE_ORIGINAL,
      tags: ['javascript', 'css', 'html', 'angular'],
      date: '2022-06-27T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/rpg-angular-v2`,
        figma: '',
        site: 'https://fescherer.github.io/rpg-angular-v2',
      },
      images: ['overview.gif', 'image-overview.webp', 'image-dark-mode.webp', 'image-dark-mode-form.webp', 'image-home.webp'],
      title: t['rpg-v2'].title,
      description: t['rpg-v2'].description,
    },
    {
      id: 'morse-secret-scripter',
      type: TYPE_ORIGINAL,
      tags: ['javascript', 'css', 'html', 'react'],
      date: '2024-06-30T10:00:00.000Z',
      links: {
        github: `${OWNER_CONFIGS.github_profile}/morse-secret-scripter`,
        figma: '',
        site: 'https://morse-secret-scripter.felipescherer.com',
      },
      images: ['thumb.webp'],
      title: t['morse-secret-scripter'].title,
      description: t['morse-secret-scripter'].description,
    },
  ])
}
