import type { Metadata } from 'next'
import { Lora, Poppins } from 'next/font/google'
import './globals.css'
import React from 'react'
import { ProgressBarProvider } from '@/providers/progress-bar.provider'
import { Footer } from '@/components/Footer'
import 'react-multi-carousel/lib/styles.css'

const lora = Lora({
  subsets: ['latin'],
  variable: '--font-title',
  display: 'swap',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-text',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lora.variable} ${poppins.variable} bg-layer-0 font-text text-on-layer-0-l2`}>
        <ProgressBarProvider>
          {children}
          <Footer />
        </ProgressBarProvider>
      </body>
    </html>
  )
}
